### ISSUE TITLE
Suggestion: dotnet new tool

### ISSUE THREAD

**Issue by kirkone** [RehanSaeed/EditorConfig#16]
Hi,

I thought it would be a good idea to have a `dotnet new editorconfig`

Maybe we can have something like @paule96 build here:
https://github.com/paule96/paule96.DotNetTemplate.GitIgnore

This is not an Issue, instead it should be used for discussion.

What do you think?

**Comment by RehanSaeed** [comment]
This is a good idea. I've thought about it a few times. I already own a templates NuGet package that it could be added to, or I could add it to a brand new one (not sure what is best).

https://github.com/Dotnet-Boxed/Templates

**Comment by kenlefeb** [comment]
> ...or I could add it to a brand new one (not sure what is best).

I think you should offer it both ways. It's only slightly more maintenance, but there's a much larger audience that will be interested in just the `.editorconfig` file and don't want all your templates, but those who like your package of templates can just get it with everything else.

**Comment by RehanSaeed** [comment]
Thanks @kenlefeb. Noted and on the TODO list.

**Comment by RehanSaeed** [comment]
Fixed in https://github.com/Dotnet-Boxed/Templates/pull/737
