### ISSUE TITLE
A severity must be specified on modifier preferences 

### ISSUE THREAD

**Issue by ddieppa** [RehanSaeed/EditorConfig#38]
### Describe the bug

when open the `editorconfig` file getting a message (EC104):
> A severity must be specified 

![image](https://user-images.githubusercontent.com/10607192/96136979-0da48300-0eca-11eb-9511-236eb3303a79.png)

### To Reproduce

Open `editorconfig` in Visual Studio

### Expected behaviour

don't see the squiggle lines.

**Comment by RehanSaeed** [comment]
@ddieppa Thank you for your PR. I've published a new release with your changes.
