### ISSUE TITLE
csharp_using_directive_placement = inside_namespace don't warn about using outside namespace

### ISSUE THREAD

**Issue by philippedurocher** [RehanSaeed/EditorConfig#43]
version 1.6.1 had `csharp_using_directive_placement = inside_namespace:warning`

Since version 2.0.0 removed the `:warning` I dont get the warnings and Quick Action don't suggest to move usings inside namespace

**Comment by RehanSaeed** [comment]
Are you using the latest version of VS? There were breaking changes are called out in https://github.com/RehanSaeed/EditorConfig/pull/42.

**Comment by philippedurocher** [comment]
This is my VS Version (About dialog) Microsoft Visual Studio Professional 2019 Version 16.8.2

**Comment by RehanSaeed** [comment]
I tried it and you're correct.

The EditorConfig VS extension is complaining that `csharp_*` and `dotnet_style_` properties need a severity and others don't. I don't really understand what's going on.

According to https://github.com/dotnet/roslyn/issues/39827 this change should have gone out already.

https://github.com/dotnet/roslyn/pull/48580 suggests that there were further changes to go out in 16.9.

**Comment by RehanSaeed** [comment]
I've requested some clarification in https://github.com/dotnet/roslyn/issues/44201.

**Comment by Xeevis** [comment]
I have same problem with Visual Studio Code using Omnisharp. it had [Roslyn updated to 3.8.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.7) 2 days ago and it doesn't take into account any rules missing severity either.

**Comment by RehanSaeed** [comment]
https://github.com/RehanSaeed/EditorConfig/issues/43 may be the cause of this issue.

**Comment by cars10w** [comment]
Ran into the same thing today.

I have to explicitly set the severity for it to behave correctly:
```
csharp_style_var_for_built_in_types = true:suggestion
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_var_elsewhere = true:suggestion
```

Otherwise these settings are not picked up at all.

**Comment by RehanSaeed** [comment]
@cars10w Did fixing https://github.com/RehanSaeed/EditorConfig/issues/43 fix this issue for you?

**Comment by cars10w** [comment]
@RehanSaeed What fix do you exactly mean?

**Comment by Xeevis** [comment]
I think 2.0.0 breaking changes were released way ahead of their time. Current syntax isn't deprecated yet, the #44201 issue isn't closed, it's just a backlog not even planned for 16.9. 

PR [Make the ':severity' suffix in editorconfig code style value optional](https://github.com/dotnet/roslyn/issues/44201) milestoned for 16.9 Preview 2 that released yesterday just makes the current syntax optional.

**Comment by RehanSaeed** [comment]
@Xeevis You may be right. My initial understanding was that 16.8 would bring in the breaking changes. It seems to work too but not for some settings.

I'll get https://github.com/RehanSaeed/EditorConfig/issues/43 fixed and if that doesn't resolve the issue we should revert PR https://github.com/dotnet/roslyn/issues/44201.
