### ISSUE TITLE
Wrong scope for dotnet severity 

### ISSUE THREAD

**Issue by cars10w** [RehanSaeed/EditorConfig#44]
Hi,

currently the [severity for dotnet_analyzer_diagnostic](https://github.com/RehanSaeed/EditorConfig/blob/4bf2cd64f9d0a733a8f4a679be1cdfb873cd8027/.editorconfig#L85) is under the 'Makefile' scope.

I guess it should be somewhere under `[*.{cs,csx,cake,vb,vbx}]`.

**Comment by RehanSaeed** [comment]
I can't believe I missed that!
