### ISSUE TITLE
New Settings in VS 16.10

### ISSUE THREAD

**Issue by RehanSaeed** [RehanSaeed/EditorConfig#48]
VS 16.10 adds new settings. Settings are suffixed with `_experimental`. Wait for it to be released before adding.

See https://github.com/dotnet/roslyn/pull/50358
```
# IDE2000, AllowMultipleBlankLines
dotnet_style_allow_multiple_blank_lines_experimental = true
# IDE2001, AllowEmbeddedStatementsOnSameLine
csharp_style_allow_embedded_statements_on_same_line_experimental = true
# IDE2002, AllowBlankLinesBetweenConsecutiveBraces
csharp_style_allow_blank_lines_between_consecutive_braces_experimental = true
# IDE2003, AllowStatementImmediatelyAfterBlock
dotnet_style_allow_statement_immediately_after_block_experimental = true
# IDE2004, AllowBlankLineAfterColonInConstructorInitializer
csharp_style_allow_blank_line_after_colon_in_constructor_initializer_experimental = true
```

See https://github.com/dotnet/roslyn/pull/49990
```
dotnet_style_namespace_match_folder
```

See https://github.com/dotnet/roslyn/issues/55005
```
csharp_style_prefer_null_check_over_type_check
```

**Comment by T-0pel** [comment]
Hi, are there any news on when these will be released? We are mainly interested in the dotnet_style_namespace_match_folder, is there any way to enable it now in VS 16.10?

**Comment by RehanSaeed** [comment]
I'll take a look soon. Documentation is a little lacking.

**Comment by RehanSaeed** [comment]
This is now fixed by https://github.com/RehanSaeed/EditorConfig/pull/59.

The experimental settings have still not been made generally available, so moved those to https://github.com/RehanSaeed/EditorConfig/issues/60.
