### ISSUE TITLE
Adding .editorconfig breaks TreatWarningsAsErrors

### ISSUE THREAD

**Issue by JimBobSquarePants** [RehanSaeed/EditorConfig#56]
### Describe the bug

Adding the `.editorconfig` file from [repo main](https://github.com/RehanSaeed/EditorConfig/tree/7b1927edffbe299873225026f61ac1ee7ae743e7) breaks `TreatWarningsAsErrors`

### To Reproduce

1. Download the attached project [ErrorsTest.zip](https://github.com/RehanSaeed/EditorConfig/files/6652373/ErrorsTest.zip)
2. Set build configuration to `Release` and build.
3. StyleCop warnings are not treated as errors and do not cause the build to fail.
4. Remove `.editorconfig` file and rebuild. Build will fail.

### Expected behaviour

When the build configuration is set to release the build should fail.

### Rules

Provide links to any [rules](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) in question.

**Comment by JimBobSquarePants** [comment]
Removing this line appears to fix the issue.

https://github.com/RehanSaeed/EditorConfig/blob/7b1927edffbe299873225026f61ac1ee7ae743e7/.editorconfig#L71-L74

Related issue
https://github.com/dotnet/roslyn/issues/43051

**Comment by RehanSaeed** [comment]
Thanks @JimBobSquarePants! I was following that Roslyn thread and thought this was fixed since they closed the issue but perhaps not.

Which version of VS are you using? `dotnet_analyzer_diagnostic.severity` should have been working since VS 16.9 onwards but I wonder if there have been bug fixes in 16.10 or 16.11 preview.

**Comment by JimBobSquarePants** [comment]
No worries 😄 
I'm using VS 16.10.

**Comment by RehanSaeed** [comment]
Raised new issue https://github.com/dotnet/roslyn/issues/55541.

**Comment by JimBobSquarePants** [comment]
Looks like there was a fix for this issue. Perhaps it can be closed now?

https://github.com/dotnet/roslyn/pull/58460

**Comment by RehanSaeed** [comment]
Looks like the fix was rolled out in 17.2. Closing. Thanks for reporting.
