### ISSUE TITLE
Support for .razor files

### ISSUE THREAD

**Issue by kirkone** [RehanSaeed/EditorConfig#68]
Maybe I did something wrong but is there a way to be able to use all the c# settings also in *.razor files?

**Comment by RehanSaeed** [comment]
The .editorconfig does not currently have special support for this file type and relies on the defaults:

```
[*]
charset = utf-8
indent_style = space
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true
```

Is there something that should be changed?

**Comment by kirkone** [comment]
The default rules are working fine.
What I want is the C# rules work in @code blocks.

When I got it right this might be related to this issue:
https://github.com/dotnet/razor-tooling/issues/4406

So, I think we have to wait for this to be completed.

I wonder if the will also bring .razor support for `dotnet build`

**Comment by RehanSaeed** [comment]
Looks like all we can do is wait. Closing for now but feel free to reopen if there is something to do here. Thank you!
