### ISSUE TITLE
Version 4.1.0 still says "4.0.0" on the file header

### ISSUE THREAD

**Issue by julealgon** [RehanSaeed/EditorConfig#69]
### Describe the bug

Latest version on the project is 4.1.0 as per https://github.com/RehanSaeed/EditorConfig/releases , however when looking at the file's contents, the header still says it is version 4.0.0:

https://github.com/RehanSaeed/EditorConfig/blob/4b0d5bcbe7069cb0828c43a8ac7c42d607e93fa2/.editorconfig#L1-L2

Aparently, the update date also doesn't match with the newest version.

### Expected behaviour

File version should match the release version to avoid confusion for consumers.

**Comment by RehanSaeed** [comment]
This was my bad, I've now corrected it.
