### ISSUE TITLE
Is there a rule to control empty line between class members declaration

### ISSUE THREAD

**Issue by Rwing** [RehanSaeed/EditorConfig#72]
like this question https://stackoverflow.com/questions/54729468/formatting-rule-to-have-blank-line-between-class-member-declarations

**Comment by RehanSaeed** [comment]
Not that I know of but this is where StyleCop can help.

**Comment by Rwing** [comment]
@RehanSaeed The StyleCop was too heavy, so I wanted to use the editorconfig to control the code style
